eureka:
    client:
        service-url:
            defaultZone: http://localhost:8862/eureka
    instance:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
logging:
    level:
        org:
            hibernate:
                SQL: debug
server:
    port: ${PORT:0}
spring:
    application:
        name: ms-mascotas
    cloud:
        loadbalancer:
            ribbon:
                enable: false
    datasource:
        driver-class-name: org.postgresql.Driver
        password: admin
        url: jdbc:postgresql://localhost/bd-catalogo-mascotas-postgres?useSSL=false
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
#        hibernate:
#            ddl-auto: update
